---
- name: Get the current content view version
  ansible.builtin.command: >
    hammer content-view version list
    --content-view {{ content_view_name }}
    --organization "{{ katello_organization }}"
    --per-page 1
    --fields id
  register: cv_version_list
  changed_when: false
  delegate_to: "{{ lpkat_host }}"
  become: true

- name: Extract the version ID from command output
  ansible.builtin.set_fact:
    cv_version_id: "{{ cv_version_list.stdout_lines | select('match', '^[0-9]+$') | first }}"
