---
- name: Get the latest content view version
  ansible.builtin.include_tasks: get_version_id.yml

- name: Promote the latest version to Production
  ansible.builtin.command: >
    hammer content-view version promote
    --id {{ cv_version_id }}
    --organization "{{ katello_organization }}"
    --to-lifecycle-environment Production
  delegate_to: "{{ lpkat_host }}"
  become: true

- name: Publish a new version
  ansible.builtin.command: >
    hammer content-view publish
    --name {{ content_view_name }}
    --organization "{{ katello_organization }}"
    --description "Automatic publish via Semaphore"
  delegate_to: "{{ lpkat_host }}"
  become: true

- name: Get the newly published content view version
  ansible.builtin.include_tasks: get_version_id.yml

- name: Promote the new version to Test only
  ansible.builtin.command: >
    hammer content-view version promote
    --id {{ cv_version_id }}
    --organization "{{ katello_organization }}"
    --to-lifecycle-environment Test
  delegate_to: "{{ lpkat_host }}"
  become: true
