---
- name: Check existing snapshots for this VM
  ansible.builtin.command: >
    pvesh get /nodes/{{ proxmox_node }}/qemu/{{ proxmox_vmid }}/snapshot
  delegate_to: "{{ proxmox_api_host }}"
  remote_user: "{{ proxmox_ssh_user }}"
  vars:
    ansible_python_interpreter: "{{ proxmox_python_interpreter }}"
  register: cleanup_snapshot_list
  changed_when: false

- name: "Remove the {{ snapshot_label | default('ansible_patching') }} snapshot if it exists"
  ansible.builtin.command: >
    pvesh delete /nodes/{{ proxmox_node }}/qemu/{{ proxmox_vmid }}/snapshot/{{ snapshot_label | default('ansible_patching') }}
  delegate_to: "{{ proxmox_api_host }}"
  remote_user: "{{ proxmox_ssh_user }}"
  vars:
    ansible_python_interpreter: "{{ proxmox_python_interpreter }}"
  when: (snapshot_label | default('ansible_patching')) in cleanup_snapshot_list.stdout
